# Generated by Django 5.2.8 on 2025-11-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='developer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
