# Generated by Django 5.2.8 on 2025-11-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('reviews', '0005_post_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='posts', to='genres.genre'),
        ),
    ]
