# Generated by Django - add publishers M2M to Post

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0001_initial'),
        ('reviews', '0007_post_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publishers',
            field=models.ManyToManyField(blank=True, related_name='posts', to='publishers.publisher'),
        ),
    ]
